# Project: GymReservation
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o Gymres.o
LINKOBJ  = main.o Gymres.o
LIBS     = -L"E:/programs/Dev-Cpp/MinGW64/lib" -L"E:/programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"E:/programs/Dev-Cpp/MinGW64/include" -I"E:/programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/programs/Dev-Cpp/MinGW64/include" -I"E:/programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = GymReservation.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Gymres.o: Gymres.cpp
	$(CPP) -c Gymres.cpp -o Gymres.o $(CXXFLAGS)
